### ISSUE TITLE
feature.js:58 TypeError: symbol.asSVG is not a function

### ISSUE THREAD

**Issue by dehmer** [syncpoint/ODINv2#50]
TypeError: symbol.asSVG is not a function
    at svg (symbol.js:16:1)
    at OptionStore._callee$ (feature.js:56:1)
    at tryCatch (feature.js:2:1)
    at Generator.<anonymous> (feature.js:2:1)
    at Generator.next (feature.js:2:1)
    at asyncGeneratorStep (feature.js:13:1)
    at _next (feature.js:14:1)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
_callee$ @ feature.js:58

**Comment by dehmer** [comment]
fixed.
